
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery")
require("popper.js")
require("bootstrap")
require("../utilities/sorting.js")
require("../utilities/password_confirmation.js")
require("../utilities/form_inline.js")
require("../utilities/passage_progress.js")
require("./badge.js")
require("../utilities/test_timer.js")
